### ISSUE TITLE
bot keeps not sending inputs 

### ISSUE THREAD

**Issue by twitchplayskh** [FabeGabe/BeamPlays#1]
i run the bot on my beam stream it  is going to a ps1 emu cmds work for a bit then stop . if i go and re click the emu they work. i do not think its the emu as my twitch plays bot works ok with the emu

**Comment by FabeGabe** [comment]
I will look into this myself, thanks for your patience.

**Comment by twitchplayskh** [comment]
no need i have it working

**Comment by FabeGabe** [comment]
Alright! Take care!
